title: CameronW
author: Cameron Walker
email: me@cameronwalker.nz

description: ""
url: "https://t94xr.github.io"
baseurl: ""
twitter_username: ""
github_username: "t94xr"

plugins:
  - jekyll-feed

permalink: /posts-/:year-:slug/
